version: "3.8"

services:
    api:
        build:
            ./api/
        ports:
            - 5000:3000
        volumes:
            - "data-volume:/database"

volumes:
    data-volume:
        external: true