version: "3.8"

services:
    api:
        build:
            ./api/
        ports:
            - 5000:3000
        volumes:
            - "data-volume:/database"
    ui:
        build:
            ./ui/
        ports:
            - 8080:80

volumes:
    data-volume:
        external: true